spring:
  datasource:
    url: jdbc:postgresql://localhost:5544/db
    username: user
    password: 12345
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mvc:
    async:
      request-timeout: 600000 # 10 minutes

logging:
  level:
    org:
      springframework:
        cache: TRACE

auth:
  token: strong

executors:
  transaction-handling:
    queue-size: 10000
    threads-min: 1
    threads-max: 8
    keep-threads-seconds: 60
  postponed-transaction-handling:
    threads-max: 8