spring:
  datasource:
    url: jdbc:postgresql://localhost:5544/db
    username: user
    password: 12345
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mvc:
    async:
      request-timeout: 600000 # 10 minutes
  application:
    name: tps

logging:
  level:
    org:
      springframework:
        cache: TRACE

logstash:
  url: logstash:4560

auth:
  token: strong