spring:
  datasource:
    url: jdbc:postgresql://localhost:5544/db
    username: user
    password: 12345
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

auth:
  token: strong

executors:
  transaction-handling:
    queue-size: 10000
    threads-min: 1
    threads-max: 8
    keep-threads-seconds: 60